// src/lib/components/notification-panel/notifications-panel.svelte
<script lang="ts">
  import {
    Button,
    HeaderAction,
    ImageLoader,
    ToastNotification,
    Truncate,
  } from "carbon-components-svelte";
  import Notification from "carbon-icons-svelte/lib/Notification.svelte";
  import NotificationNew from "carbon-icons-svelte/lib/NotificationNew.svelte";
  import { UserNotificationStore, refreshUserNotificationStore } from "../../stores";
  import "./notifications-panel.scss";
  import { roundDurationToString } from "./utils";
  import { typeIsString } from "@siaikin/utils";
  import { markUserNotificationAsRead } from "../../http-interface";
  import type { UserNotification } from "../../http-interface";
  import WakapiLogo from "../../assets/images/wakapi-logo.png";
  import GitHubLogo from "../../assets/images/github-logo-white.svg";

  export let isOpen = false;

  const logoMap = {
    wakapi: WakapiLogo,
    github: GitHubLogo,
  };
  const blockClass = `${"hd"}--notifications-panel`;

  function handleOpenNewTab(e: PointerEvent, notification: UserNotification): void {
    const element = e.currentTarget as HTMLDivElement;

    const url = element.dataset.url;
    if (!typeIsString(url)) return;

    // https://developer.chrome.com/docs/lighthouse/best-practices/external-anchors-use-rel-noopener/
    window.open(url, "_blank", "noopener,noreferrer");

    markAsRead(notification);
  }

  function markAsRead(notification: UserNotification): void {
    markUserNotificationAsRead(notification.id);
    refreshUserNotificationStore();
  }

  async function markAllAsRead() {
    await markUserNotificationAsRead();
    refreshUserNotificationStore();
  }
</script>

<div class="{`${blockClass}__wrapper`}">
  <HeaderAction
    on:open
    on:close
    isOpen="{isOpen}"
    transition="{false}"
    icon="{$UserNotificationStore.notifications.length > 0 ? NotificationNew : Notification}"
    closeIcon="{$UserNotificationStore.notifications.length > 0 ? NotificationNew : Notification}"
  >
    <div class="{blockClass}" on:click="{(e) => e.stopPropagation()}">
      <div class="{`${blockClass}__header-container`}">
        <div class="{`${blockClass}__header-flex`}">
          <h3 class="{`${blockClass}__header`}">Notifications</h3>
          <Button
            class="{`${blockClass}__dismiss-button`}"
            kind="ghost"
            size="small"
            on:click="{markAllAsRead}">Clear all</Button
          >
        </div>
        <!--      <Toggle size="sm" class="{`${blockClass}__do-not-disturb-toggle`}">-->
        <!--        <span slot="labelA">Do not disturb</span>-->
        <!--        <span slot="labelB">Do not disturb</span>-->
        <!--      </Toggle>-->
      </div>
      <div class="{`${blockClass}__main-section`}">
        {#each $UserNotificationStore.notifications as notification, index}
          {@const now = Date.now()}
          <ToastNotification
            role="notification"
            fullWidth
            kind="{notification.kind}"
            data-url="{notification.link}"
            on:click="{(e) => handleOpenNewTab(e, notification)}"
            on:close="{() => markAsRead(notification)}"
          >
            <svelte:fragment slot="title">
              <Truncate>{roundDurationToString(notification.originCreateAt - now)}</Truncate>
            </svelte:fragment>
            <svelte:fragment slot="subtitle">
              <Truncate title="{notification.title}">
                {#if logoMap[notification.origin]}
                  <ImageLoader
                    class="{`${blockClass}__subtitle-icon`}"
                    src="{logoMap[notification.origin]}"
                  />
                {/if}
                {notification.title}
              </Truncate>
            </svelte:fragment>
            <svelte:fragment slot="caption">
              <Truncate title="{notification.caption}">{notification.caption}</Truncate>
            </svelte:fragment>
          </ToastNotification>
        {/each}
      </div>
    </div>
  </HeaderAction>
</div>

// src/lib/components/notifications-panel/notifications-panel.tsx
import { Icon } from "@iconify-icon/solid";
import { UserNotificationsContext } from "../../contextes";
import { roundDurationToString } from "./utils";
import { notUAN, typeIsString } from "@siaikin/utils";
import { markUserNotificationAsRead } from "../../http-interface";
import type { UserNotification } from "../../http-interface";
import { For, mergeProps, Show, VoidProps } from "solid-js";

import "./notifications-panel.scss";

export default function NotificationsPanel(props: VoidProps<{ expanded: boolean }>) {
  const [userNotifications, { refresh }] = UserNotificationsContext.useContext();
  refresh().then();

  const mergedProps = mergeProps({ expanded: false }, props);

  const logoMap: Record<string, string> = {
    wakapi: "simple-icons:wakatime",
    github: "carbon:logo-github"
  };
  const blockClass = `${"hd"}--notifications-panel`;

  async function handleOpenNewTab(notification: UserNotification) {
    if (!typeIsString(notification.link)) return;

    // https://developer.chrome.com/docs/lighthouse/best-practices/external-anchors-use-rel-noopener/
    window.open(notification.link, "_blank", "noopener,noreferrer");

    await markAsRead(notification);
  }

  async function markAsRead(notification: UserNotification) {
    await markUserNotificationAsRead(notification.id);
    await refresh();
  }

  async function markAllAsRead() {
    await markUserNotificationAsRead();
    await refresh();
  }

  return (
    <cds-header-panel
      id="notifications-panel"
      class={`${blockClass}__wrapper`}
      expanded={mergedProps.expanded}
    >
      <div class={blockClass}>
        <div class={`${blockClass}__header-container`}>
          <div class={`${blockClass}__header-flex`}>
            <h3 class={`${blockClass}__header`}>Notifications</h3>
            <cds-button
              class={`${blockClass}__dismiss-button`}
              kind="ghost"
              size="small"
              onClick={markAllAsRead}
            >
              Clear all
            </cds-button>
          </div>
        </div>
        <div class={`${blockClass}__main-section`}>
          <For each={userNotifications}>
            {(notification) => {
              const now = Date.now();
              return (
                <cds-toast-notification
                  class="mb-0.5"
                  role="notification"
                  kind={notification.kind}
                  caption={roundDurationToString(notification.originCreateAt - now)}
                  on:cds-notification-closed={() => markAsRead(notification)}
                >
                  <div
                    slot="title"
                    title={notification.title}
                    class="flex justify-start items-center w-48 text-xs"
                  >
                    <Show when={notUAN(logoMap[notification.origin])}>
                      <Icon
                        width={16}
                        height={16}
                        class={`${blockClass}__subtitle-icon`}
                        icon={logoMap[notification.origin]}
                      />
                    </Show>
                    <span class="truncate">{notification.title}</span>
                  </div>
                  <div
                    slot="subtitle"
                    class="cursor-pointer mt-2"
                    onClick={[handleOpenNewTab, notification]}
                  >
                    {notification.caption}
                  </div>
                </cds-toast-notification>
              );
            }}
          </For>
        </div>
      </div>
    </cds-header-panel>
  );
}
