// src/routes/(portal)/system-process/index.tsx
import {
  ProcessRealtimeMemoryUsageChart,
  ProcessRealtimeCpuUsageChart
} from "../../../lib/components/charts";
import { modifyCollectStat } from "../../../lib/http-interface/server-send-event";
import { debounce } from "@siaikin/utils";
import { handleInput } from "../../../lib/utils/felte-utils";
import { createEffect, Match, on, Switch } from "solid-js";
import { createForm } from "@felte/solid";

import "./styles.scss";

export default function Index() {
  const handleModifyProcessCollectStat = debounce(
    (sortField: string, max: number) =>
      modifyCollectStat({
        system: { enable: false },
        process: { enable: true, sortField, max }
      }),
    250
  );

  const {
    form: controlForm,
    data: controlFormData,
    handleSubmit: handleControlFormSubmit,
    setData: setControlFormData
  } = createForm({
    onSubmit: async () => {
      handleModifyProcessCollectStat(controlFormData().sortBy, controlFormData().refreshInterval);
    },
    initialValues: {
      refreshInterval: 16,
      sortBy: "memoryUsage"
    }
  });
  createEffect(on(controlFormData, () => handleControlFormSubmit()));

  return (
    <div class="system-process-container flex flex-col h-full">
      <div class="flex-none">
        <form class="control-form flex items-center" use:controlForm>
          <span class="flex-1" />
          <cds-form-item class="flex-none">
            <cds-slider
              label-text={`Top ${controlFormData().refreshInterval}`}
              min={1}
              max={60}
              value={controlFormData().refreshInterval}
              on:cds-slider-changed={(event: CustomEvent) =>
                handleInput({ name: "refreshInterval", setter: setControlFormData }, event)
              }
            >
              <cds-slider-input type="number" />
            </cds-slider>
          </cds-form-item>
          <cds-form-item class="flex-none">
            <cds-select
              label-text="Sort by"
              value={controlFormData().sortBy}
              onInput={[handleInput, { name: "sortBy", setter: setControlFormData }]}
            >
              <cds-select-item value="memoryUsage">Memory usage</cds-select-item>
              <cds-select-item value="cpuUsage">Cpu usage</cds-select-item>
              <cds-select-item value="networkUsage">Network usage</cds-select-item>
            </cds-select>
          </cds-form-item>
        </form>
      </div>

      <div class="flex-auto">
        <cds-tile class="h-full w-full">
          <Switch>
            <Match when={controlFormData().sortBy === "memoryUsage"}>
              <ProcessRealtimeMemoryUsageChart />
            </Match>
            <Match when={controlFormData().sortBy === "cpuUsage"}>
              <ProcessRealtimeCpuUsageChart />
            </Match>
          </Switch>
        </cds-tile>
      </div>
    </div>
  );
}

// src/routes/(portal)/system-process/+page.svelte
<script lang="ts">
  import {
    ProcessRealtimeMemoryUsageChart,
    ProcessRealtimeCpuUsageChart,
  } from "../../../lib/components/charts";
  import {
    Column,
    Grid,
    Row,
    Tile,
    FormGroup,
    Form,
    Slider,
    Select,
    SelectItem,
  } from "carbon-components-svelte";
  import { modifyCollectStat } from "../../../lib/http-interface/server-send-event";
  import { debounce } from "@siaikin/utils";
  import { mounted } from "../../../lib/stores/lifecycle";

  import "./system-process.scss";

  const isMounted = mounted();
  const handleModifyProcessCollectStat = debounce(
    (sortField: string, max: number) =>
      modifyCollectStat({
        system: { enable: false },
        process: { enable: true, sortField, max },
      }),
    250
  );

  let controlFormData = {
    refreshInterval: 16,
    sortBy: "memoryUsage",
  };

  $: {
    if ($isMounted) {
      handleModifyProcessCollectStat(controlFormData.sortBy, controlFormData.refreshInterval);
    }
  }
</script>

<div class="system-process-container">
  <Form class="control-form">
    <span style="flex: 1 1 auto"></span>
    <!--    <FormGroup legendText="Refresh interval (S)">-->
    <!--      <Slider min="{1}" max="{60}" bind:value="{controlFormData.refreshInterval}" />-->
    <!--    </FormGroup>-->
    <FormGroup legendText="{`Top ${controlFormData.refreshInterval}`}">
      <Slider min="{1}" max="{60}" bind:value="{controlFormData.refreshInterval}" />
    </FormGroup>
    <FormGroup legendText="Sort by">
      <Select bind:selected="{controlFormData.sortBy}">
        <SelectItem value="memoryUsage" text="Memory usage" />
        <SelectItem value="cpuUsage" text="Cpu usage" />
        <SelectItem value="networkUsage" text="Network usage" />
      </Select>
    </FormGroup>
  </Form>

  <Grid fullWidth padding noGutter class="chart-container">
    <Row class="process-chart-row">
      <Column>
        <Tile class="process-chart-tile">
          {#if controlFormData.sortBy === "memoryUsage"}
            <ProcessRealtimeMemoryUsageChart options="{{ toolbar: false }}" class="process-chart" />
          {:else if controlFormData.sortBy === "cpuUsage"}
            <ProcessRealtimeCpuUsageChart class="process-chart" />
          {/if}
        </Tile>
      </Column>
    </Row>
  </Grid>
</div>

<style lang="scss">
  .system-process-container {
    height: 100%;
  }
</style>
