// src/routes/(portal)/dashboard/github-grid.tsx
import { notUAN } from "@siaikin/utils";
import { GitHub } from "../../../lib/third-party";
import { createMemo, createResource } from "solid-js";
import { Icon } from "@iconify-icon/solid";

export default function GitHubGrid() {
  // const [breakpoint, { smallerThan, largerThan }] = BreakpointsContext.useContext();

  const [userInfo] = createResource(async () => await GitHub.getUserInfo());

  const gitHubHost = createMemo(() => (notUAN(userInfo()) ? userInfo()?.url : ""));
  // const gitHubUserAvatar = createMemo(() => (notUAN(userInfo()) ? userInfo().avatarUrl : ""));
  const gitHubUserName = createMemo(() => (notUAN(userInfo()) ? userInfo()?.name : ""));
  const gitHubUserFollowerCount = createMemo(() =>
    notUAN(userInfo()) ? userInfo()?.followerCount : 0
  );
  const gitHubUserFollowingCount = createMemo(() =>
    notUAN(userInfo()) ? userInfo()?.followingCount : 0
  );
  // const gitHubUserWatcherCount = createMemo(() =>
  //   notUAN(userInfo()) ? userInfo().repositoryInfo.watcherCount : 0
  // );
  // const gitHubUserForkCount = createMemo(() =>
  //   notUAN(userInfo()) ? userInfo().repositoryInfo.forkCount : 0
  // );
  // const gitHubUserStargazerCount = createMemo(() =>
  //   notUAN(userInfo()) ? userInfo().repositoryInfo.stargazerCount : 0
  // );
  const gitHubUserContributionWeeks = createMemo(
    () =>
      userInfo()
        ?.contributionCalendar.weeks.map(({ contributionDays }) =>
          contributionDays.map((day) => ({
            count: day.contributionCount,
            date: day.date,
            level:
              GitHub.ContributionLevel[
                day.contributionLevel as keyof typeof GitHub.ContributionLevel
              ]
          }))
        )
        .flat() ?? []
  );
  const legendText = createMemo(
    () => `${gitHubUserFollowerCount()} followers · ${gitHubUserFollowingCount()} following`
  );

  return (
    <div class="github-grid cds--css-grid cds--css-grid--condensed">
      <div class="cds--css-grid-column cds--sm:col-span-4 cds--md:col-span-8 cds--lg:col-span-16">
        <form class="control-form">
          <cds-link href={gitHubHost()} target="_blank">
            <Icon width={32} height={32} icon="carbon:logo-github" title="Power by GitHub" />
          </cds-link>
          <header class="flex-auto w-0">
            <h4 class="truncate" title={gitHubUserName()}>
              {gitHubUserName()}
            </h4>
            <p class="truncate" title={legendText()}>
              <Icon icon="octicon:people-16" inline /> {legendText()}
            </p>
          </header>
        </form>
      </div>

      <div class="cds--css-grid-column cds--sm:col-span-4 cds--md:col-span-8 cds--lg:col-span-16">
        <cds-tile class="github-tile">
          <GitHub.GitHubContributionsChart days={gitHubUserContributionWeeks()} />
        </cds-tile>
      </div>
    </div>
  );
}

// src/routes/(portal)/github-grid.svelte
<script lang="ts">
  import {
    Column,
    Form,
    Grid,
    ImageLoader,
    Link,
    Row,
    Truncate,
    truncate,
    breakpointObserver,
    Tile,
  } from "carbon-components-svelte";
  import Icon from "@iconify/svelte";
  import { notUAN } from "@siaikin/utils";
  import { getUserInfo, ContributionsChart, ContributionLevel } from "../../lib/third-party/github";
  import type { UserInfo } from "../../lib/third-party/github";
  import { mounted } from "../../lib/stores";
  import GitHubLogo from "$lib/assets/images/github-logo.svg";

  const size = breakpointObserver();
  const isMounted = mounted();

  let userInfo: UserInfo | undefined;
  isMounted.subscribe(async (mounted) => {
    if (!mounted) return;

    userInfo = await getUserInfo();
  });

  $: githubHost = notUAN(userInfo) ? userInfo.url : "";
  $: githubUserAvatar = notUAN(userInfo) ? userInfo.avatarUrl : "";
  $: githubUserName = notUAN(userInfo) ? userInfo.name : "";
  $: githubUserFollowerCount = notUAN(userInfo) ? userInfo.followerCount : 0;
  $: githubUserFollowingCount = notUAN(userInfo) ? userInfo.followingCount : 0;
  $: githubUserWatcherCount = notUAN(userInfo) ? userInfo.repositoryInfo.watcherCount : 0;
  $: githubUserForkCount = notUAN(userInfo) ? userInfo.repositoryInfo.forkCount : 0;
  $: githubUserStargazerCount = notUAN(userInfo) ? userInfo.repositoryInfo.stargazerCount : 0;
  $: githubUserContributionWeeks = notUAN(userInfo)
    ? userInfo.contributionCalendar.weeks
        .map(({ contributionDays }) =>
          contributionDays.map((day) => ({
            count: day.contributionCount,
            date: day.date,
            level: ContributionLevel[day.contributionLevel],
          }))
        )
        .flat()
    : [];
</script>

<Grid condensed class="github-grid">
  <Row>
    <Column sm="{4}" md="{8}" lg="{16}">
      <Form class="control-form">
        <Link href="{githubHost}" target="_blank" style="margin-left: 0.5rem">
          <ImageLoader fadeIn alt="Power by GitHub" style="width: 2rem" src="{GitHubLogo}" />
        </Link>
        <header style="flex: 1 1 auto; width: 0">
          <h4 use:truncate title="{githubUserName}">{githubUserName}</h4>
          <Truncate>
            <Icon icon="octicon:people-16" inline />
            {githubUserFollowerCount}
            followers ·
            {githubUserFollowingCount}
            following
          </Truncate>
        </header>
      </Form>
    </Column>
  </Row>

  <Row>
    <Column sm="{4}" md="{8}" lg="{16}">
      <Tile class="github-tile">
        <!--        <Icon icon="octicon:star-16" inline />-->
        <!--        {githubUserStargazerCount}-->
        <!--        <Icon icon="octicon:eye-16" inline />-->
        <!--        {githubUserWatcherCount}-->
        <!--        <Icon icon="octicon:repo-forked-16" inline />-->
        <!--        {githubUserForkCount}-->

        <ContributionsChart days="{githubUserContributionWeeks}" />
      </Tile>
    </Column>
  </Row>
</Grid>
