// src/routes/(portal)/settings/+page.svelte
<script lang="ts">
  import {
    Accordion,
    AccordionItem,
    Button,
    ExpandableTile,
    Form,
    ImageLoader,
    InlineLoading,
    Modal,
    OutboundLink,
    TextInput,
    Truncate,
  } from "carbon-components-svelte";
  import MobileIcon from "carbon-icons-svelte/lib/Mobile.svelte";
  import { bind2FAAuthenticatorApp, disable2FA, get2FAQRCode } from "$lib/http-interface";
  import type { User } from "$lib/http-interface";
  import { INTERACTIVE_INTERVAL } from "../../../lib/utils/interactive_interval";

  import "./+page.scss";

  export let data: { user: User };
  // 用于保存路由跳转的 Promise. 用于在路由跳转时, 切换页面状态提示.
  let redirectPromise: Promise<void>;

  // 启用/禁用 2FA 的逻辑
  let is2FAEnabled = data.user.enable2FA;
  let isConfirmDisable2FAModalOpened = false;
  let trigger2faEnableStatePromise: Promise<void>;
  async function handleTrigger2FAEnableState() {
    trigger2faEnableStatePromise = disable2FA();
    await trigger2faEnableStatePromise;

    isConfirmDisable2FAModalOpened = false;

    redirectPromise = INTERACTIVE_INTERVAL.gotoAfterMoment("/login");
  }

  // 绑定 Authenticator App 的逻辑
  let authenticatorAppFormData = { code: "" };
  let bindingAuthenticatorAppPromise: Promise<void>;
  async function handleBindingAuthenticatorApp() {
    bindingAuthenticatorAppPromise = bind2FAAuthenticatorApp(authenticatorAppFormData.code);
    await bindingAuthenticatorAppPromise;

    redirectPromise = INTERACTIVE_INTERVAL.gotoAfterMoment("/login");
  }
</script>

<Accordion align="start">
  <AccordionItem open disabled="{!is2FAEnabled}" title="Two-factor authentication">
    <svelte:fragment slot="title">
      <div style="display: flex; justify-content: space-between; align-items: center">
        <span>Two-factor authentication</span>
        {#if is2FAEnabled}
          <Button
            kind="danger"
            size="small"
            on:click="{(ev) => (ev.stopPropagation(), (isConfirmDisable2FAModalOpened = true))}"
          >
            Disable
          </Button>
        {:else}
          <Button kind="primary" size="small" on:click="{() => (is2FAEnabled = true)}">
            Enable
          </Button>
        {/if}
      </div>
    </svelte:fragment>

    <ExpandableTile tileCollapsedIconText="" tileExpandedIconText="">
      <svelte:fragment slot="above">
        <strong>
          <MobileIcon class="icon--inline" /> Authenticator app
        </strong>

        <!-- todo 优化字体大小 fontSize: 12px -->
        <Truncate>
          Use an authentication app or browser extension to get two-factor authentication codes when
          prompted.
        </Truncate>
      </svelte:fragment>
      <svelte:fragment slot="below">
        <Form on:submit="{handleBindingAuthenticatorApp}" on:click="{(ev) => ev.stopPropagation()}">
          <p>
            Authenticator apps and browser extensions like <OutboundLink
              href="https://support.1password.com/one-time-passwords/">1Password</OutboundLink
            >, <OutboundLink href="https://authy.com/guides/github/">Authy</OutboundLink>, <OutboundLink
              href="https://www.microsoft.com/en-us/account/authenticator/"
              >Microsoft Authenticator</OutboundLink
            >, etc. generate one-time passwords that are used as a second factor to verify your
            identity when prompted during sign-in.
          </p>
          <div style="margin-bottom: 0.5rem"></div>

          <h6>Scan the QR code</h6>
          <div style="margin-bottom: 0.5rem"></div>

          <p>Use an authenticator app or browser extension to scan.</p>
          <div style="width: 144px;">
            {#await get2FAQRCode()}
              <ImageLoader>
                <svelte:fragment slot="loading"><InlineLoading /></svelte:fragment>
              </ImageLoader>
            {:then dataUrl}
              <ImageLoader src="{dataUrl}" />
            {:catch error}
              <ImageLoader>
                <svelte:fragment slot="error">{error}</svelte:fragment>
              </ImageLoader>
            {/await}
          </div>

          <h6>Verify the code from the app</h6>
          <div style="margin-bottom: 1rem"></div>

          {#await bindingAuthenticatorAppPromise}
            <TextInput disabled hideLabel value="{authenticatorAppFormData.code}" />
          {:then _}
            <TextInput
              hideLabel
              placeholder="XXXXXX"
              maxlength="6"
              bind:value="{authenticatorAppFormData.code}"
            />
          {:catch error}
            <TextInput
              hideLabel
              placeholder="XXXXXX"
              invalid
              invalidText="{error}"
              maxlength="6"
              bind:value="{authenticatorAppFormData.code}"
            />
          {/await}

          <div style="margin-bottom: 1rem"></div>

          {#await bindingAuthenticatorAppPromise}
            <Button disabled kind="ghost">
              <InlineLoading status="active" description="binding..." />
            </Button>
          {:then _}
            {#if !!redirectPromise}
              <Button disabled kind="ghost">
                <InlineLoading status="finished" description="bind success" />
              </Button>
            {:else}
              <Button type="submit" disabled="{authenticatorAppFormData.code.length !== 6}">
                Save
              </Button>
            {/if}
          {:catch _}
            <Button type="submit" disabled="{authenticatorAppFormData.code.length !== 6}">
              Save
            </Button>
          {/await}
        </Form>
      </svelte:fragment>
    </ExpandableTile>
  </AccordionItem>
</Accordion>

<Modal
  danger
  bind:open="{isConfirmDisable2FAModalOpened}"
  modalHeading="Disable two-factor authentication?"
  primaryButtonDisabled="{!!trigger2faEnableStatePromise}"
  primaryButtonIcon="{trigger2faEnableStatePromise ? InlineLoading : undefined}"
  primaryButtonText="Disable"
  secondaryButtonText="Cancel"
  on:click:button--primary="{handleTrigger2FAEnableState}"
  on:click:button--secondary="{() => (isConfirmDisable2FAModalOpened = false)}"
>
  After disable two-factor authentication, you need to log in again.
</Modal>

<style lang="scss">
</style>

// src/routes/(portal)/settings/index.tsx
import {
  bind2FAAuthenticatorApp,
  disable2FA,
  get2FAQRCode,
  getCurrentUser
} from "../../../lib/http-interface";
import { useInteractiveInterval } from "../../../lib/utils/interactive_interval";
import { createEffect, createResource, createSignal, Show } from "solid-js";
import { createForm } from "@felte/solid";
import { Icon } from "@iconify-icon/solid";
import { handleInput } from "../../../lib/utils/felte-utils";
import { createResourceDefer } from "../../../lib/utils/create-resource";

import "./styles.scss";
import { SystemInfoAccordionItem } from "./system-info";

export default function Index() {
  const { gotoAfterMoment } = useInteractiveInterval();
  const [userInfo, { refetch }] = createResource(async () => await getCurrentUser());

  // 启用/禁用 2FA 的逻辑
  const [is2FAEnabled, set2FAEnabled] = createSignal();
  createEffect(() => set2FAEnabled(userInfo()?.enable2FA));
  const [confirmDisable2FAModalOpened, setConfirmDisable2FAModalOpened] = createSignal(false);

  const [disable2FAResult, { refetch: handleDisable2FA }] = createResourceDefer(async () => {
    await disable2FA();
    await refetch();

    setConfirmDisable2FAModalOpened(false);

    await gotoAfterMoment("/login");
  });

  // 绑定 Authenticator App 的逻辑
  const {
    form: authenticatorAppForm,
    data: authenticatorAppFormData,
    handleSubmit: handleAuthenticatorAppFormSubmit,
    setData: setAuthenticatorAppFormData,
    isSubmitting: isSubmittingAuthenticatorAppForm
  } = createForm({
    onSubmit: async () => {
      await bind2FAAuthenticatorApp(authenticatorAppFormData().code);

      await gotoAfterMoment("/login");
    },
    initialValues: { code: "" }
  });

  const [qrcodeUrl] = createResource(() => get2FAQRCode());

  return (
    <>
      <cds-accordion alignment="start">
        <cds-accordion-item open={is2FAEnabled()} disabled={!is2FAEnabled()}>
          <div slot="title" class="flex justify-between items-center">
            <span>
              <Icon icon="carbon:two-factor-authentication" inline={true} /> Two-factor
              authentication
            </span>
            <Show
              when={is2FAEnabled()}
              fallback={
                <cds-button kind="primary" size="sm" on:click={() => set2FAEnabled(true)}>
                  Enable
                </cds-button>
              }
            >
              <cds-button
                kind="danger"
                size="sm"
                onClick={() => setConfirmDisable2FAModalOpened(true)}
              >
                Disable
              </cds-button>
            </Show>
          </div>

          <cds-expandable-tile expanded={true} with-interactive={true}>
            <cds-tile-above-the-fold-content slot="above-the-fold-content" class="h-16">
              <strong>
                <Icon icon="carbon:mobile" inline={true} width={16} height={16} /> Authenticator app
              </strong>

              <div class="truncate">
                Use an authentication app or browser extension to get two-factor authentication
                codes when prompted.
              </div>
            </cds-tile-above-the-fold-content>
            <cds-tile-below-the-fold-content style={{ height: "420px" }}>
              <form use:authenticatorAppForm>
                <cds-stack gap={2}>
                  <p>
                    Authenticator apps and browser extensions like{" "}
                    <cds-link href="https://support.1password.com/one-time-passwords/">
                      1Password
                    </cds-link>
                    ,<cds-link href="https://authy.com/guides/github/">Authy</cds-link>,
                    <cds-link href="https://www.microsoft.com/en-us/account/authenticator/">
                      Microsoft Authenticator
                    </cds-link>
                    , etc. generate one-time passwords that are used as a second factor to verify
                    your identity when prompted during sign-in.
                  </p>
                  <h6>Scan the QR code</h6>
                  <p>Use an authenticator app or browser extension to scan.</p>

                  <Show
                    when={!qrcodeUrl.loading}
                    fallback={
                      <cds-inline-loading status="active">Loading QR code...</cds-inline-loading>
                    }
                  >
                    <img src={qrcodeUrl()} alt="qrcode url" />
                  </Show>

                  <h6>Verify the code from the app</h6>

                  <cds-form-item>
                    <cds-text-input
                      hide-label=""
                      placeholder="XXXXXX"
                      maxlength="6"
                      onInput={[handleInput, { name: "code", setter: setAuthenticatorAppFormData }]}
                    />
                  </cds-form-item>

                  <Show
                    when={isSubmittingAuthenticatorAppForm()}
                    fallback={
                      <cds-Button
                        type="submit"
                        disabled={authenticatorAppFormData().code.length !== 6}
                        onClick={[handleAuthenticatorAppFormSubmit]}
                      >
                        Save
                      </cds-Button>
                    }
                  >
                    <cds-Button disabled="" kind="ghost">
                      <cds-inline-loading status="active">binding...</cds-inline-loading>
                    </cds-Button>
                  </Show>
                </cds-stack>
              </form>
            </cds-tile-below-the-fold-content>
          </cds-expandable-tile>
        </cds-accordion-item>
        <SystemInfoAccordionItem />
      </cds-accordion>

      <cds-modal open={confirmDisable2FAModalOpened()}>
        <cds-modal-header>
          <cds-modal-heading>Disable two-factor authentication?</cds-modal-heading>
        </cds-modal-header>

        <cds-modal-body>
          After disable two-factor authentication, you need to log in again.
        </cds-modal-body>

        <cds-modal-footer>
          <cds-modal-footer-button
            kind="secondary"
            disabled={disable2FAResult.loading}
            onClick={[setConfirmDisable2FAModalOpened, false]}
          >
            Cancel
          </cds-modal-footer-button>
          <cds-modal-footer-button
            kind="danger"
            disabled={disable2FAResult.loading}
            onClick={[handleDisable2FA]}
          >
            <Show
              when={!disable2FAResult.loading}
              fallback={<cds-inline-loading status="active">Disabling...</cds-inline-loading>}
            >
              Disable
            </Show>
          </cds-modal-footer-button>
        </cds-modal-footer>
      </cds-modal>
    </>
  );
}
